### ISSUE TITLE
Screen Freezes Sometimes #StatixOS
#Bug

### ISSUE THREAD

**Issue by ExxoShy** [angelomds42/spes_releases#2]
Screen sometimes freezes and becomes unresponsive

**Comment by KiZakiXD** [comment]
> Screen sometimes freezes and becomes unresponsive

Oh, that's right, I'm also experiencing the same problem, if it's stuck, the phone is like it's dead when I click the power button, it won't turn on, I have to restart it with the power button and volume up, that's very annoying
